<Project>
  <PropertyGroup>
    <Version>1.0.61</Version>
    <AssemblyVersion>1.0.61.0</AssemblyVersion>
    <FileVersion>1.0.61.0</FileVersion>
    <LangVersion>14.0</LangVersion>
    <Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings>
    <Deterministic>true</Deterministic><AnalysisLevel>latest</AnalysisLevel>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>
</Project>
